In [1]:
import torch
import math

In [9]:
# The torch.empty() call allocates memory for the tensor, but does not initialize it with any values 
# so what you’re seeing is whatever was in memory at the time of allocation.
x = torch.empty(3,4)

In [10]:
# Zero matrix
zeros = torch.zeros(2,3)

# Ones
ones = torch.ones(2,3)

# Random 
torch.manual_seed(1234)
random = torch.rand(2,3)


In [13]:
torch.manual_seed(1234)
r1 = torch.rand(2,3)
print(r1)

r2 = torch.rand(2,3)
print(r2)

torch.manual_seed(1234)
r3 = torch.rand(2,3)
print(r3)

r4 = torch.rand(2,3)
print(r4)

# r1 and r3 are identical like r2 and r4

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


In [14]:
# shapes
x = torch.empty(2,2,3)
print(x.shape)
print(x)

torch.Size([2, 2, 3])
tensor([[[1.5766e-19, 1.0256e-08, 1.0255e-08],
         [3.1644e+12, 6.9362e-07, 6.7140e-07]],

        [[6.5923e-10, 1.3033e+16, 2.1707e-18],
         [7.0952e+22, 1.7748e+28, 1.8176e+31]]])


In [16]:
rx = torch.rand_like(x)
print(rx.shape)
print(rx)

torch.Size([2, 2, 3])
tensor([[[0.9665, 0.7399, 0.4517],
         [0.4757, 0.7842, 0.1525]],

        [[0.6662, 0.3343, 0.7893],
         [0.3216, 0.5247, 0.6688]]])


In [17]:
# tensor data types
x = torch.ones((2,3), dtype=torch.int16)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [27]:
y = torch.rand((2,3), dtype=torch.float64)*100
print(y)

tensor([[52.0624,  2.7672, 99.3424],
        [78.2850, 62.6016, 94.2548]], dtype=torch.float64)


In [28]:
z = y.to(torch.int32)
print(z)

tensor([[52,  2, 99],
        [78, 62, 94]], dtype=torch.int32)


In [34]:
#math
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [40]:
#powers 

p2 = twos**torch.tensor([[1,2],[3,4]])
print(p2)

p4 = fours**torch.tensor([[5,4],[3,2]])
print(p4)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[1024.,  256.],
        [  64.,   16.]])


In [45]:
a = torch.rand(2,3)
b = torch.rand(3,2)
print(a*b)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [50]:
# broadcast

rand = torch.rand(2,4)
doubled = rand * (torch.ones(1,4) * 2)
print(rand)
print('----')
print(doubled)
print('----')
print(rand*2)

tensor([[0.3819, 0.8610, 0.2775, 0.9121],
        [0.9980, 0.8427, 0.7868, 0.6861]])
----
tensor([[0.7637, 1.7219, 0.5551, 1.8242],
        [1.9960, 1.6855, 1.5735, 1.3722]])
----
tensor([[0.7637, 1.7219, 0.5551, 1.8242],
        [1.9960, 1.6855, 1.5735, 1.3722]])


In [62]:
a = torch.rand(2,4) * 4 - 1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5,0.5))

tensor([[ 1.8084,  0.8967, -0.0055,  0.4031],
        [ 0.9110,  2.2419,  0.8538,  0.4930]])
tensor([[1.8084, 0.8967, 0.0055, 0.4031],
        [0.9110, 2.2419, 0.8538, 0.4930]])
tensor([[2., 1., -0., 1.],
        [1., 3., 1., 1.]])
tensor([[ 1.,  0., -1.,  0.],
        [ 0.,  2.,  0.,  0.]])
tensor([[ 0.5000,  0.5000, -0.0055,  0.4031],
        [ 0.5000,  0.5000,  0.5000,  0.4930]])


In [63]:
d = torch.tensor([[1.,2.],[3.,4.]])
print(torch.std(d))

tensor(1.2910)


In [66]:
# copy

a = torch.ones(2,2)
b = a

In [69]:
a[0][1] = 69
print(a)
print(b)

tensor([[ 1., 69.],
        [ 1.,  1.]])
tensor([[ 1., 69.],
        [ 1.,  1.]])


In [70]:
# without modify other

a = torch.ones(2,2)
b = a.clone()

a[0][1] = 69

In [71]:
print(a)
print(b)

tensor([[ 1., 69.],
        [ 1.,  1.]])
tensor([[1., 1.],
        [1., 1.]])


In [74]:
# shape manipulation
a = torch.rand(3,256,256)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 256, 256])
torch.Size([1, 3, 256, 256])


In [75]:
c = torch.rand(1, 1, 1, 1, 1)
print(c)

tensor([[[[[0.2359]]]]])
